site_name: RocketMod Documentation
copyright: 'RocketMod is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a><br>This documentation is licensed under <a href="http://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>'
docs_dir: 'content'
repo_name: 'RocketMod/Rocket'
repo_url: 'https://github.com/RocketMod/Rocket'
edit_uri: 'https://github.com/RocketMod/Rocket.Documentation/edit/master/content/'
pages:
    - Home: index.md
    - User Guide:
        - Installation:
            - Unturned 3: user-guide/installation/unturned3.md
            - Eco: user-guide/installation/eco.md
        - Configuration: 
            - Configurations: user-guide/configuration/configurations.md
            - Translations: user-guide/configuration/translations.md
            - Permissions: user-guide/configuration/permissions.md
            - Plugins: user-guide/configuration/plugins.md
        - Plugins: 
            - Installation: user-guide/plugins/installation.md
        - Commands:
            - Rocket: user-guide/commands/rocket.md
            - Unturned 3: user-guide/commands/unturned3.md
            - Eco: user-guide/commands/eco.md
        - Support: user-guide/support.md
    - Development Guide:
#        - Concept:
#            - Code Documentation: development-guide/concept/code-documentation.md
#            - Patterns:
#                - Inversion Of Control: development-guide/concept/ioc.md
#            - Compatibility: development-guide/concept/compatibility.md
        - Getting Started:
            - Making your first plugin: development-guide/getting-started/making-your-first-plugin.md
            - Commands: development-guide/getting-started/commands.md
            - Scheduling: development-guide/getting-started/scheduling.md
            - Eventing: development-guide/getting-started/eventing.md
            - Logging: development-guide/getting-started/logging.md
            - Configurations: development-guide/getting-started/configurations.md
            - Permissions: development-guide/getting-started/permissions.md
#            - Database: development-guide/getting-started/database.md
        - Misc:
            - Migration Guide: development-guide/misc/migration-guide.md
            - List of all Services: development-guide/misc/services.md
            - List of all Events: development-guide/misc/events.md
        - Game Implementations:
            - Creating a new implementation: development-guide/game-implementations/creating-a-new-implementation.md
#            - Unturned 3:
#                - Home : development-guide/game-implementations/unturned3/index.md
#            - Eco:
#                - Home : development-guide/game-implementations/eco/index.md
    - About:
        - Documentation: about/documentation.md

theme:
  custom_dir: 'theme'
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'light blue'
  logo: 'images/rocket.svg' 
  language: 'en'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
